# Generated by Django 4.0.3 on 2023-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('duration', models.TimeField()),
                ('stcount', models.IntegerField()),
            ],
        ),
    ]
